project:
  type: website

website:
  title: "Home"
  navbar:
    right:
      - about.qmd
      #- icon: github
       # href: http2s://github.com/
      #- icon: twitter
       # href: https://twitter.com
format:
  html:
    theme: default
    css: styles.css

editor: visual

